"""Initial migration.

Revision ID: 667e2712446a
Revises: 
Create Date: 2020-06-08 12:54:00.842898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e2712446a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE table todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable = False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
